spring:
  application:
    name: learnSpring

  datasource:
    url: jdbc:postgresql://localhost:5433/learn_spring
    username: learn_spring
    password: learn_spring
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 3000

api:
  prefix: /api/v1